#!/bin/bash
# setup_nginx_proxy.sh
# 安装 nginx 并配置本地反向代理（用于 Cloudflare Zero Trust）
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 引入公共函数
# shellcheck source=common.sh
. "${SCRIPT_DIR}/common.sh"

# 如果从主入口调用，语言已初始化；否则初始化语言
init_lang
ensure_root
ensure_apt

if is_en; then
  echo -e "${GREEN}=== Nginx Reverse Proxy Setup (for Cloudflare Zero Trust) ===${NC}"
else
  echo -e "${GREEN}=== Nginx 反向代理配置（用于 Cloudflare Zero Trust）===${NC}"
fi

# ============================================
# 1. 安装 nginx
# ============================================
msg "${GREEN}1. 安装 nginx...${NC}" "${GREEN}1. Installing nginx...${NC}"
log_info "Installing nginx"

if ! command -v nginx &>/dev/null; then
  apt update
  apt install -y nginx
  log_info "nginx installed successfully"
else
  msg "${YELLOW}nginx 已安装，跳过安装步骤${NC}" "${YELLOW}nginx already installed, skipping${NC}"
  log_info "nginx already installed"
fi

# ============================================
# 2. 配置监听端口
# ============================================
DEFAULT_LISTEN_PORT="9999"
prompt_read "nginx 监听端口 (默认: ${DEFAULT_LISTEN_PORT}): " \
            "nginx listen port (default: ${DEFAULT_LISTEN_PORT}): " \
            "$DEFAULT_LISTEN_PORT" LISTEN_PORT
LISTEN_PORT="${LISTEN_PORT:-$DEFAULT_LISTEN_PORT}"

# 验证端口号
if ! [[ "$LISTEN_PORT" =~ ^[0-9]+$ ]] || [ "$LISTEN_PORT" -le 0 ] || [ "$LISTEN_PORT" -gt 65535 ]; then
  msg "${RED}无效端口号: $LISTEN_PORT${NC}" "${RED}Invalid port: $LISTEN_PORT${NC}"
  exit 1
fi

log_info "Using listen port: $LISTEN_PORT"

# ============================================
# 3. 配置后端服务
# ============================================
msg "" ""
msg "${GREEN}配置反向代理后端服务${NC}" "${GREEN}Configure reverse proxy backends${NC}"
msg "可以添加多个后端服务，每个服务需要提供路径和目标地址" \
    "You can add multiple backend services, each needs a path and target address"
msg "" ""

# 默认后端配置
PROXY_CONFIGS=()

while true; do
  CURRENT_COUNT=$((${#PROXY_CONFIGS[@]} + 1))
  
  prompt_read "请输入服务路径 (如 / 或 /api，输入 done 完成配置): " \
              "Enter service path (e.g., / or /api, type 'done' to finish): " \
              "" PROXY_PATH
  
  if [ "$PROXY_PATH" = "done" ] || [ -z "$PROXY_PATH" ]; then
    if [ ${#PROXY_CONFIGS[@]} -eq 0 ]; then
      msg "${YELLOW}至少需要配置一个后端服务${NC}" "${YELLOW}At least one backend service is required${NC}"
      continue
    fi
    break
  fi
  
  prompt_read "请输入后端地址 (如 http://127.0.0.1:3000): " \
              "Enter backend address (e.g., http://127.0.0.1:3000): " \
              "" PROXY_TARGET
  
  if [ -z "$PROXY_TARGET" ]; then
    msg "${YELLOW}后端地址不能为空，请重新输入${NC}" "${YELLOW}Backend address cannot be empty, please retry${NC}"
    continue
  fi
  
  PROXY_CONFIGS+=("${PROXY_PATH}|${PROXY_TARGET}")
  msg "${GREEN}已添加: ${PROXY_PATH} -> ${PROXY_TARGET}${NC}" \
      "${GREEN}Added: ${PROXY_PATH} -> ${PROXY_TARGET}${NC}"
  log_info "Added proxy config: ${PROXY_PATH} -> ${PROXY_TARGET}"
done

# ============================================
# 4. 生成 nginx 配置
# ============================================
msg "${GREEN}2. 生成 nginx 配置...${NC}" "${GREEN}2. Generating nginx configuration...${NC}"

NGINX_CONF_DIR="/etc/nginx/sites-available"
NGINX_CONF_ENABLED="/etc/nginx/sites-enabled"
CONF_NAME="cloudflare-proxy"
CONF_FILE="${NGINX_CONF_DIR}/${CONF_NAME}"

# 备份现有配置
if [ -f "$CONF_FILE" ]; then
  BACKUP_FILE="${CONF_FILE}.bak.$(date +%F-%H%M%S)"
  cp "$CONF_FILE" "$BACKUP_FILE"
  msg "${YELLOW}已备份现有配置到: ${BACKUP_FILE}${NC}" \
      "${YELLOW}Backed up existing config to: ${BACKUP_FILE}${NC}"
  log_info "Backed up existing config to $BACKUP_FILE"
fi

# 生成 location 块
LOCATION_BLOCKS=""
for config in "${PROXY_CONFIGS[@]}"; do
  IFS='|' read -r path target <<< "$config"
  LOCATION_BLOCKS+="
    location ${path} {
        proxy_pass ${target};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \"upgrade\";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header CF-Connecting-IP \$http_cf_connecting_ip;
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
        proxy_buffering off;
    }
"
done

# 写入配置文件
cat > "$CONF_FILE" << EOF
# Nginx reverse proxy for Cloudflare Zero Trust
# Generated by linux-server-initial on $(date '+%Y-%m-%d %H:%M:%S')
# Listen on localhost:${LISTEN_PORT} for Cloudflare Tunnel

server {
    listen 127.0.0.1:${LISTEN_PORT};
    listen [::1]:${LISTEN_PORT};
    
    server_name _;
    
    # 日志
    access_log /var/log/nginx/cloudflare-proxy-access.log;
    error_log /var/log/nginx/cloudflare-proxy-error.log;
    
    # 安全头
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    
    # Cloudflare 相关头
    real_ip_header CF-Connecting-IP;
    
    # 健康检查端点
    location /health {
        access_log off;
        return 200 "OK\\n";
        add_header Content-Type text/plain;
    }
${LOCATION_BLOCKS}
}
EOF

log_info "Generated nginx config at $CONF_FILE"

# ============================================
# 5. 启用配置
# ============================================
msg "${GREEN}3. 启用 nginx 配置...${NC}" "${GREEN}3. Enabling nginx configuration...${NC}"

# 删除默认站点（可选）
if [ -L "${NGINX_CONF_ENABLED}/default" ]; then
  prompt_read "是否禁用 nginx 默认站点? [y/N]: " \
              "Disable nginx default site? [y/N]: " \
              "n" DISABLE_DEFAULT
  if [[ "$DISABLE_DEFAULT" =~ ^[Yy]$ ]]; then
    rm -f "${NGINX_CONF_ENABLED}/default"
    msg "${YELLOW}已禁用默认站点${NC}" "${YELLOW}Default site disabled${NC}"
    log_info "Disabled default nginx site"
  fi
fi

# 创建符号链接
if [ ! -L "${NGINX_CONF_ENABLED}/${CONF_NAME}" ]; then
  ln -s "$CONF_FILE" "${NGINX_CONF_ENABLED}/${CONF_NAME}"
fi

# ============================================
# 6. 测试并重载配置
# ============================================
msg "${GREEN}4. 测试 nginx 配置...${NC}" "${GREEN}4. Testing nginx configuration...${NC}"

if nginx -t 2>&1; then
  msg "${GREEN}配置测试通过${NC}" "${GREEN}Configuration test passed${NC}"
  log_info "nginx config test passed"
else
  msg "${RED}配置测试失败，请检查配置文件${NC}" "${RED}Configuration test failed, please check config${NC}"
  log_error "nginx config test failed"
  exit 1
fi

# ============================================
# 7. 启动/重载 nginx
# ============================================
msg "${GREEN}5. 重载 nginx 服务...${NC}" "${GREEN}5. Reloading nginx service...${NC}"

systemctl enable nginx
systemctl reload nginx || systemctl restart nginx

log_info "nginx service reloaded"

# ============================================
# 8. 显示配置摘要
# ============================================
echo ""
echo -e "${GREEN}=====================================================${NC}"
if is_en; then
  echo -e "${GREEN}✅ Nginx reverse proxy configured successfully${NC}"
  echo ""
  echo -e "Listen address: ${GREEN}127.0.0.1:${LISTEN_PORT}${NC}"
  echo -e "Config file: ${GREEN}${CONF_FILE}${NC}"
  echo ""
  echo -e "Configured backends:"
  for config in "${PROXY_CONFIGS[@]}"; do
    IFS='|' read -r path target <<< "$config"
    echo -e "  ${GREEN}${path}${NC} -> ${target}"
  done
  echo ""
  echo -e "Health check: ${GREEN}http://127.0.0.1:${LISTEN_PORT}/health${NC}"
  echo ""
  echo -e "${YELLOW}Cloudflare Tunnel Configuration:${NC}"
  echo -e "In Cloudflare Zero Trust Dashboard, set the tunnel service to:"
  echo -e "  ${GREEN}http://127.0.0.1:${LISTEN_PORT}${NC}"
else
  echo -e "${GREEN}✅ Nginx 反向代理配置完成${NC}"
  echo ""
  echo -e "监听地址: ${GREEN}127.0.0.1:${LISTEN_PORT}${NC}"
  echo -e "配置文件: ${GREEN}${CONF_FILE}${NC}"
  echo ""
  echo -e "已配置的后端服务:"
  for config in "${PROXY_CONFIGS[@]}"; do
    IFS='|' read -r path target <<< "$config"
    echo -e "  ${GREEN}${path}${NC} -> ${target}"
  done
  echo ""
  echo -e "健康检查: ${GREEN}http://127.0.0.1:${LISTEN_PORT}/health${NC}"
  echo ""
  echo -e "${YELLOW}Cloudflare Tunnel 配置:${NC}"
  echo -e "在 Cloudflare Zero Trust Dashboard 中，将隧道服务设置为:"
  echo -e "  ${GREEN}http://127.0.0.1:${LISTEN_PORT}${NC}"
fi
echo -e "${GREEN}=====================================================${NC}"
